### ISSUE TITLE
Go v1.6.3 安装 gopm 失败

### ISSUE THREAD

**Issue by justqyx** [gpmgo/gopm#113]
```
➜  ~ go version
go version go1.6.3 darwin/amd64
➜  ~ go get -u github.com/gpmgo/gopm
# github.com/gpmgo/gopm
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0xf47b]

runtime stack:
runtime.throw(0x2c4900, 0x2a)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x3a70a0)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x3a70a0, 0x1, 0x12, 0x45b558)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbfe918)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x3a70a0, 0x1, 0x10000000012, 0xf11f)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x3a8b50, 0x0)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x3a8b50, 0x45b558)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x402000, 0x12, 0x45b558)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x3a0700)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/asm_amd64.s:245 fp=0xc820044988 sp=0xc820044980
runtime.mallocgc(0x120, 0x276fa0, 0x0, 0x1d7520)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/malloc.go:643 +0x869 fp=0xc820044a60 sp=0xc820044988
runtime.newobject(0x276fa0, 0xc82001a3f0)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/malloc.go:781 +0x42 fp=0xc820044a88 sp=0xc820044a60
cmd/link/internal/ld._lookup(0xc82008a240, 0xc8202fe290, 0xf, 0x0, 0x1, 0x180)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/cmd/link/internal/ld/sym.go:201 +0xf3 fp=0xc820044b00 sp=0xc820044a88
cmd/link/internal/ld.Linklookup(0xc82008a240, 0xc8202fe290, 0xf, 0x0, 0x0)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/cmd/link/internal/ld/sym.go:208 +0x48 fp=0xc820044b38 sp=0xc820044b00
cmd/link/internal/ld.readsym(0xc82008a240, 0xc820017d60, 0x27e550, 0x7, 0xc8200127d0, 0x42)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/cmd/link/internal/ld/objfile.go:187 +0x36c fp=0xc820044f80 sp=0xc820044b38
cmd/link/internal/ld.ldobjfile(0xc82008a240, 0xc820017d60, 0x27e550, 0x7, 0x2a1a45, 0xc8200127d0, 0x42)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/cmd/link/internal/ld/objfile.go:147 +0xa62 fp=0xc820045190 sp=0xc820044f80
cmd/link/internal/ld.ldobj(0xc820017d60, 0x27e550, 0x7, 0x2a1a9f, 0xc8200127d0, 0x42, 0xc820011040, 0x3a, 0x1, 0x0)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/cmd/link/internal/ld/lib.go:1351 +0x1569 fp=0xc820045400 sp=0xc820045190
cmd/link/internal/ld.objfile(0xc820022460)
	/Users/yuanxin/.gvm/gos/go1.6.3/src/cmd/link/internal/ld/lib.go:847 +0x10d9 fp=0xc820045710 sp=0xc820045400
cmd/link/internal/ld.loadlib()
	/Users/yuanxin/.gvm/gos/go1.6.3/src/cmd/link/internal/ld/lib.go:513 +0x5ce fp=0xc8200459f0 sp=0xc820045710
cmd/link/internal/ld.Ldmain()
	/Users/yuanxin/.gvm/gos/go1.6.3/src/cmd/link/internal/ld/pobj.go:214 +0x1cd3 fp=0xc820045e70 sp=0xc8200459f0
cmd/link/internal/amd64.Main()
	/Users/yuanxin/.gvm/gos/go1.6.3/src/cmd/link/internal/amd64/obj.go:44 +0x19 fp=0xc820045e78 sp=0xc820045e70
main.main()
	/Users/yuanxin/.gvm/gos/go1.6.3/src/cmd/link/main.go:27 +0x36f fp=0xc820045f50 sp=0xc820045e78
runtime.main()
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/proc.go:188 +0x2b0 fp=0xc820045fa0 sp=0xc820045f50
runtime.goexit()
	/Users/yuanxin/.gvm/gos/go1.6.3/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820045fa8 sp=0xc820045fa0
```

**Comment by Unknwon** [comment]
... 这跟 gopm 毫无关系啊。。。都是 runtime 的编译错误，你的版本可能已经不支持你所使用的操作系统了。先升级到 1.8 吧！

**Comment by justqyx** [comment]
@Unknwon 好的，升级之后就没有问题了。
